### ISSUE TITLE
Stacks.Razor repo link broken

### ISSUE THREAD

**Issue by sengiv** [StackExchange/Stacks#1257]
Found link in nuget, doesn't work.
https://github.com/StackExchange/Stacks-Razor

**Comment by giamir** [comment]
Hello @sengiv and thanks for bringing this to our attention.
The [Stacks Razor library](https://razor.stackoverflow.design/) is still in a beta phase internally at Stack Overflow.
We haven't officially open sourced the code in the StackExchange organisation yet but you can expect that to happen relatively soon.
Closing this issue since that URL is the correct location where the source code will be hosted.

**Comment by sengiv** [comment]
Thanks! The project looks very promising, can't wait for it to be open. 😁
