### ISSUE TITLE
Stacks - how to use it?

### ISSUE THREAD

**Issue by surfmuggle** [StackExchange/Stacks#1260]
From the intro

> Stacks is Stack Overflow’s design system. It includes the resources needed to create consistent, predictable interfaces and workflows that conform to Stack Overflow’s principles, design language, and best practices.

It is unclear to me how would i use stacks. 

 1. Do i need to be a customer of [stackoverflow.co/teams/](https://stackoverflow.co/teams/use-cases/devops/) or similar?
 2. Is it like bootstrap? 
 3. Can it be used for any application?

**Comment by dancormier** [comment]
> From the intro
> 
> > Stacks is Stack Overflow’s design system. It includes the resources needed to create consistent, predictable interfaces and workflows that conform to Stack Overflow’s principles, design language, and best practices.
> 
> It is unclear to me how would i use stacks.
> 
>     1. Do i need to be a customer of [stackoverflow.co/teams/](https://stackoverflow.co/teams/use-cases/devops/) or similar?

Nope, you don't need to be a customer to use Stacks. Stacks is open sourced and is released under the MIT License so it can be used in your projects. See our [LICENSE.md](https://github.com/StackExchange/Stacks/blob/develop/LICENSE.MD) for details.

>     2. Is it like bootstrap?

In some ways. Both Bootstrap and Stacks include a component library, atomic CSS classes, and convenience features like built-in color modes and custom theming. Basically, they both are primarily tools to build consistent UIs.

In other ways though, they're distinct. First and foremost, Stacks is built primarily with stackoverflow.com in mind so we're guided towards building specific components and utilities for that context. Bootstrap is general purpose. There are hundreds of minor distinctions between the two tools that I won't get into at the moment, because I'd be typing all night 😂

I think our [_Using Stacks_](https://stackoverflow.design/product/guidelines/using-stacks/) docs page could be a good start for someone to understand _why_ and _how_ they might want to use Stacks. From there, you can go down the sidebar to checkout some other the features, atomic classes, and components included in the Stacks library.

>     3. Can it be used for any application?

"_Any_" might be going too far. I'm biased, but I think Stacks is a great tool to help you build the front end of a web app.
