### ISSUE TITLE
Feature request: green "confirm" button

### ISSUE THREAD

**Issue by benjamin-hodgson** [StackExchange/Stacks#260]
I want to implement a design like this one:

![screenshot 2019-02-19 at 15 02 16](https://user-images.githubusercontent.com/3857587/53043864-77e7f480-3457-11e9-9e76-071923c2d05e.png)

At the moment I have `s-btn s-btn__filled bg-green-400 fc-white`, which I find a bit messy (and probably doesn't look as nice as it should).

Could we have an `s-btn__confirm` or similar which produces a button with a green background?

I can try to build this in a PR if you like

**Comment by aaronshekey** [comment]
We killed green buttons entirely, since they were only used in Talent, and rarely.

This is a perfect case that's handled by `s-btn s-btn__primary`. I would swap the button classes for those since adding the confirm button will require quite a bit of CSS and is another type of button to support across our network and its many themes :v:
