### ISSUE TITLE
Should our accordions use Details/Summary tags?

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#266]
Apparently it's [a good way to create them](https://css-tricks.com/quick-reminder-that-details-summary-is-the-easiest-way-ever-to-make-an-accordion/). And there's the newish way [Github is using these tags for modals](https://marcus.io/blog/progressive-enhanced-menus-details-summary). With our JavaScript support in flux, does it make sense to explore something like this for accordions?

The browser support is a bit worrisome, but it degrades sorta gracefully in that all links are default open.

<img width="884" alt="screen shot 2019-02-25 at 8 41 09 am" src="https://user-images.githubusercontent.com/1172461/53341332-43ea5480-38d9-11e9-9f09-fffe06cd1056.png">

**Comment by balpha** [comment]
Given the various downsides (lack of complete browser support, questionable accessibility, questionable semantics, lack of flexibility), I'm wondering what advantages you're expecting from this that would offset these issues? You're hinting at two things in this regard:

> Apparently it's a good way to create them

That's not really what that articles says, it only says that it's an *easy* way to create them

> With our JavaScript support in flux

I'm not sure what exactly you're referring to here, since accordions are one of the few things that we already *do* have JS for.

Can you go into the details of what you think we might gain by exploring this route?

**Comment by TedGoas** [comment]
Just wanted to get y'alls thoughts on it here. I understand the semantics and browser support concerns, but saw this as a potential "gateway drug" into possibly not needed as much JS to support interactions. Accordions was just the first example, but sounds like this isn't an ideal path forward.

If we continue forging ahead with Stimulus, I guess this isn't an issue worth discussing further.

**Comment by aaronshekey** [comment]
Stimulus isn't going anywhere. I think it's a sound choice that we're sticking to, @balpha or no.
