### ISSUE TITLE
Toast z-index is outranked by many things

### ISSUE THREAD

**Issue by Shog9** [StackExchange/Stacks#341]
> *The smell of that buttered toast simply talked to Toad, and with no uncertain voice...*

## Description

`.s-toast` is defined with zi-popovers z-index, currently 2000. That's outranked by a lot of more permanent stuff: navbars, banners, dialogs, *the background of dialogs*... 

Given these are *temporary* messages, users won't always have time to scroll or dismiss other elements in order to find the toast - they should be given a high enough index to ensure that they're not likely to be inadvertently obscured.

Current work-around is to ensure that the message is parented by an element that itself has a high z-index. 

## To Reproduce

1. Add nav, banner, dialog elements to a page. 
2. Attach an s-toast banner to the body
3. Note that it falls behind them all: 
![partially obscured toast](https://user-images.githubusercontent.com/4950451/59535196-89915400-8ead-11e9-953a-9945ce406bf1.png)

## Expected behavior

Should be above everything while visible. What is more important than toast?

## Additional resources

Chat convo: https://chat.meta.stackexchange.com/transcript/message/7776380#7776380

**Comment by bnickel** [comment]
For color,, the one time I had both displayed, I put the toast inside the modal.  In our codebase, that would be something like `StackExchange.helpers.showToast(..., { $parent: $modal });`.  Otherwise, I've been dismissing the dialog and showing the toast if it's a friendly message. That probably wouldn't work for things like non-Stacks modals though or when the toast is unrelated.  We'd also need to check the behavior works on mobile if that becomes a common practice.
