### ISSUE TITLE
Thought: Provide atomic overrides?

### ISSUE THREAD

**Issue by hellohynes** [StackExchange/Stacks#52]
I was reading [this article from GOV.UK about how they set up their type and spacing](https://designnotes.blog.gov.uk/2018/02/19/developing-new-typography-and-spacing-for-gov-uk-frontend/). One tidbit in there is that they provide override classes using `.govuk-!-`, which I didn't know were a thing.

What do people think about providing normal and important atomic classes for Stacks? This would allow developers to use `.show()` and `.hide()` for jQuery (using `.d-none` overrides any local styles jQuery applies). Is that too much overhead? Do we default to adding `!important` and provided non-important version as needed?

**Comment by balpha** [comment]
I agree with Brian's answer [here](https://stackoverflow.com/c/stack-overflow/a/536/68) (Stack Overflow employee-only link).

> Conceptually, you should really be removing `d-none` from an element that no longer going to be `display:none` so I would start with `.removeClass('d-none')`.  Otherwise, `d-none` or `dno` would just be a flat out lie.

An additional thing to keep in mind is that jQuery's `.show()` doesn't ever really work if the previous hiding happened via anything other than `.hide()`.

When you call `.hide()` on an element, jQuery

- checks if the elment has an inline style with the `display` property, and if so, remembers that value
- sets `display` to `none` on the element via inline style

When you call `.show()` on an element, jQuery

- checks if it has a "remembered" (from a above) `display` value, and if so, re-sets the elements style to that
- otherwise, it sets the element's `display` style to whatever is the default for this kind of element (e.g. `inline` for `<span>`, `block` for `<div>`).

Therefore, let's say you have this element:

    <div class="grid gs8 d-none">

Even if `d-none` were *not* `!important`, calling `show()` would not do the right thing, because it would do this:

    <div class="grid gs8 d-none" style="display: block">

-- and `block` is the wrong value for `display` here, because a `.grid` should be `flex`. And flex boxes in particular are pretty pervasive in our code, so chances for this happening are pretty good.

If we wanted to handle this stuff in a reasonable way, the only thing I can think of is monkey-patch jQuery's `.show()` to remove a `d-none` class if present, and only fall back to its usual behavior otherwise.

But a non-important atomic `display-...` class wouldn't really help.

**Comment by hellohynes** [comment]
We will not pursue providing important and non-important classes at this time.
