### ISSUE TITLE
Segoe descenders are getting cut off in form elements

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#699]
![image](https://user-images.githubusercontent.com/1369864/121819236-90483280-cc51-11eb-971d-817e8338cc45.png)

**Comment by mukunku** [comment]
Just to add to the discussion, on my pages if I remove the `line-height` from the `.s-select > select` style the text is rendered fully in the dropdown:
![image](https://user-images.githubusercontent.com/4502154/157540313-5cb21c22-c145-40d4-9691-e94dfe7ae798.png)
But I'm leaving the text cutoff for now since we should fix this systemically instead of piecemeal.

**Comment by aaronshekey** [comment]
This should be fixed by #863
